version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
  redis:
    image: "redis"
    restart: always
    container_name: "redis"
  celery:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/core
    command: [ 'celery', '-A', 'core', 'worker', '-l', 'info' ]