### Загрузка новых товаров
POST {{Host}}/partner/update
Authorization: Token {{Token}}
Content-Type:application/json

{
  "url":
  "https://raw.githubusercontent.com/macosib/Diplom_Netology/master/data/upload.yaml"
}

### Просмотр статуса магазина
GET {{Host}}/partner/state/1
Authorization: Token {{Token}}
Content-Type:application/json

### Изменение статуса магазина
PUT {{Host}}/partner/state/1
Authorization: Token {{Token}}
Content-Type:application/json

{
  "state": false
}

### Просмотр категорий
GET {{Host}}/categories
Authorization: Token {{Token}}

### Просмотр магазинов
GET {{Host}}/shops
Authorization: Token {{Token}}

### Просмотр товаров
GET {{Host}}/products
Authorization: Token {{Token}}

### Просмотр товаров
GET {{Host}}/products?category_id=224
Authorization: Token {{Token}}



###
POST {{Host}}/basket
Authorization: Token {{Token}}
Content-Type:application/json

 {
   "items":
   [
     {"product_info": 1,
     "quantity": 4
},
     {"product_info": 2,
     "quantity": 3
}
   ]
   }
###
PUT {{Host}}/basket
Authorization: Token {{Token}}
Content-Type:application/json

 {
   "items":
   [
     {"product_info": 1,
     "quantity": 1
},
     {"product_info": 2,
     "quantity": 3
}
   ]
 }

###
DELETE {{Host}}/basket
Authorization: Token {{Token}}
Content-Type:application/json
